"""
Evaluation Plan JSON schema definitions.

These Pydantic models define the structure of AI-generated evaluation plans.
The AI Requirement Extractor produces EvaluationPlan JSON,
which the Evaluation Engine executes against validators.
"""

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field


class CheckItem(BaseModel):
    """A single check to perform during evaluation.

    Each check maps to a registered validator by its `type` key.
    The `params` dict provides arguments specific to that validator.
    """

    type: str = Field(
        ...,
        description="Validator type key from the registry, e.g. 'vlan_exists', 'ospf_network'",
    )
    params: dict[str, Any] = Field(
        default_factory=dict,
        description="Dynamic parameters for the validator",
    )
    description: str = Field(
        "",
        description="Human-readable description of what this check verifies",
    )
    weight: float = Field(
        1.0,
        ge=0.0,
        description="Scoring weight for this check",
    )
    required: bool = Field(
        True,
        description="If True, failing this check means overall failure regardless of score",
    )


class EvaluationPlan(BaseModel):
    """Complete evaluation plan generated by AI from a professor's question.

    This is the contract between the AI Requirement Extractor and the Evaluation Engine.
    """

    topic: str = Field(
        ...,
        description="Primary topic area, e.g. 'OSPF', 'VLAN', 'STP'",
    )
    description: str = Field(
        "",
        description="Summary of what this evaluation checks",
    )
    checks: list[CheckItem] = Field(
        ...,
        min_length=1,
        description="List of individual checks to perform",
    )
    total_points: float = Field(
        100.0,
        ge=0.0,
        description="Maximum achievable score",
    )
    pass_threshold: float = Field(
        0.7,
        ge=0.0,
        le=1.0,
        description="Minimum fraction of total_points needed to pass",
    )


class ValidatorParamSchema(BaseModel):
    """Describes a single parameter that a validator accepts.

    Used to generate the AI extractor's system prompt so it knows
    what parameters each validator type requires.
    """

    name: str
    type: str  # "string", "integer", "boolean", "list[string]", etc.
    required: bool = True
    description: str = ""
    example: Any = None


class ValidatorCatalogEntry(BaseModel):
    """Describes a registered validator for the AI extractor catalog.

    The AI uses this catalog to decide which checks to include
    in the evaluation plan and what parameters to supply.
    """

    type_key: str = Field(..., description="Unique key, e.g. 'vlan_exists'")
    description: str = Field(..., description="What this validator checks")
    topic: str = Field("", description="Primary topic area")
    params: list[ValidatorParamSchema] = Field(default_factory=list)
    examples: list[dict[str, Any]] = Field(
        default_factory=list,
        description="Example param dicts for the AI",
    )


class CheckResult(BaseModel):
    """Result of executing a single check."""

    check_type: str
    check_description: str
    passed: bool
    message: str
    details: dict[str, Any] = Field(default_factory=dict)
    score: float = Field(0.0, ge=0.0, le=1.0)
    weight: float = 1.0
    required: bool = True


class EvaluationResult(BaseModel):
    """Complete result of an evaluation run."""

    plan: EvaluationPlan
    check_results: list[CheckResult]
    total_score: float
    max_score: float
    percentage: float
    passed: bool
    summary: str
    errors: list[str] = Field(default_factory=list)
